version: '2'
services:

  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/fork-project
    depends_on:
      - webpack-dev
    command: [python, test_app/app.py]

  webpack-dev:
    ports:
      - "2992:2992"
      - "8080:8080"
    build: .
    volumes:
      - ./:/fork-project
    command: [npm, start]    
